#!/bin/sh

export HURLORD_TERM='foot -o font=Hack:pixelsize=30' # CHANGE THIS if you are using another 
#terminal or set to nothing if you want it to run in the current terminal
export OUTPUT_BASE="/tmp/hurlord" # CHANGE THIS if you want your queries to be persistant
export DEFAULT_ENVSPACE_NAME="dev" # CHANGE THIS if you want your queries to be persistant


export HURLORD_HOME=$(dirname $(readlink "$0")) 
export PATH="$HURLORD_HOME:$PATH"
export LISTEN_ADDRESS="/tmp/hurlordSocket$RANDOM" 
export NNN_OPENER="$HURLORD_HOME/sender"
export EDITOR="$HURLORD_HOME/sender"

[ ! -d "$OUTPUT_BASE" ] && mkdir "$OUTPUT_BASE"
# [ ! -d "$PWD/.envs" ] && mkdir "$PWD/.envs"
# [ ! -f "$PWD/.envs/$DEFAULT_ENVSPACE_NAME" ] && touch "$PWD/.envs/$DEFAULT_ENVSPACE_NAME

$HURLORD_TERM nvim -u $HURLORD_HOME/init.lua --listen $LISTEN_ADDRESS $@
